// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1vKZ9GpWKRfnDHuviCL2we5W8V0ClY4',
    appId: '1:324321966537:web:d17488acf2f9fac0e65018',
    messagingSenderId: '324321966537',
    projectId: 'fire-track-60af1',
    authDomain: 'fire-track-60af1.firebaseapp.com',
    storageBucket: 'fire-track-60af1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9jbQLOBCvg_9qnJwNOKQyvmA5xxlWnjI',
    appId: '1:324321966537:android:b4938df33f352563e65018',
    messagingSenderId: '324321966537',
    projectId: 'fire-track-60af1',
    storageBucket: 'fire-track-60af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTl3RIcbJss_5dwKI1QSuuRaBP8mtHP4',
    appId: '1:324321966537:ios:fb182933d624aa77e65018',
    messagingSenderId: '324321966537',
    projectId: 'fire-track-60af1',
    storageBucket: 'fire-track-60af1.appspot.com',
    iosBundleId: 'com.example.fireTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTl3RIcbJss_5dwKI1QSuuRaBP8mtHP4',
    appId: '1:324321966537:ios:bb5874ab7afbe7fae65018',
    messagingSenderId: '324321966537',
    projectId: 'fire-track-60af1',
    storageBucket: 'fire-track-60af1.appspot.com',
    iosBundleId: 'com.example.fireTrack.RunnerTests',
  );
}
